FOLDER_PREFIX = "run_"
SAMPLE_DATA_FILE = "sample_data.txt"
TARGET_SEQUENCE = "target_sequence"
PROMOTER = "promoter"
PROMOTER_START = "promoter_start"
PROMOTER_END = "promoter_end"
INPUT_DATA_FILE_NAME = "input_data.json"
SETTINGS_FILE_NAME = "run_settings.json"

FILTER_TRANSCRIPT_INCOMPLETE = "filter_transcript_incomplete"
FILTER_TRANSCRIPT_PROTEIN_CODING = "filter_transcript_protein_coding"
FILTER_TRANSCRIPT_START_CODON = "filter_transcript_start_codon"
FILTER_TRANSCRIPT_STOP_CODON = "filter_transcript_stop_codon"
